
'use client';

import { useState, RefObject } from 'react';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import { useToast } from '@/hooks/use-toast';
import { format } from 'date-fns';

interface PdfOptions {
  companyName: string;
  documentTitle: string;
}

interface UseDownloadPdfProps {
  reportRef: RefObject<HTMLDivElement>;
  fileName: string;
  options: PdfOptions;
}

export function useDownloadPdf({ reportRef, fileName, options }: UseDownloadPdfProps) {
  const [isDownloading, setIsDownloading] = useState(false);
  const { toast } = useToast();

  const handleDownload = async () => {
    const element = reportRef.current;
    if (!element) {
      toast({ variant: 'destructive', title: 'Error', description: 'Could not find the content to download.' });
      return;
    }

    setIsDownloading(true);
    try {
      const canvas = await html2canvas(element, { scale: 2, useCORS: true, backgroundColor: null });
      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF({ orientation: 'p', unit: 'mm', format: 'a4' });
      const PADDING = 15;
      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = pdf.internal.pageSize.getHeight();
      
      const addHeader = () => {
        pdf.setFontSize(18);
        pdf.setFont('helvetica', 'bold');
        pdf.setTextColor(40);
        pdf.text(options.companyName, pdfWidth - PADDING, 20, { align: 'right' });
        
        pdf.setFontSize(10);
        pdf.setFont('helvetica', 'normal');
        pdf.setTextColor(100);
        pdf.text(options.documentTitle, pdfWidth - PADDING, 26, { align: 'right' });
      };

      const addFooter = (pageNumber: number, totalPages: number) => {
          pdf.setFontSize(8);
          pdf.setTextColor(150);
          pdf.text(`Page ${pageNumber} of ${totalPages}`, pdfWidth / 2, pdfHeight - 10, { align: 'center' });
          pdf.text('Generated by RAK Safety Hub', PADDING, pdfHeight - 10);
          pdf.text(format(new Date(), 'PPP'), pdfWidth - PADDING, pdfHeight - 10, { align: 'right' });
      };

      const contentWidth = pdfWidth - (PADDING * 2);
      const contentImageHeight = (canvas.height * contentWidth) / canvas.width;
      const contentStartY = 40;
      const pageContentHeight = pdfHeight - contentStartY - (PADDING);

      let heightLeft = contentImageHeight;
      let position = 0; // Tracks the Y position of the image slice
      let page = 1;

      // Estimate total pages
      const totalPages = Math.ceil(contentImageHeight / pageContentHeight);

      // Add first page
      addHeader();
      pdf.addImage(imgData, 'PNG', PADDING, contentStartY, contentWidth, contentImageHeight);
      addFooter(page, totalPages);
      heightLeft -= pageContentHeight;

      while (heightLeft > 0) {
        page++;
        position -= pageContentHeight;
        pdf.addPage();
        addHeader();
        pdf.addImage(imgData, 'PNG', PADDING, position + contentStartY, contentWidth, contentImageHeight);
        addFooter(page, totalPages);
        heightLeft -= pageContentHeight;
      }
      
      pdf.save(`${fileName}.pdf`);
      toast({ title: 'Success', description: 'PDF downloaded successfully.' });

    } catch (err) {
      console.error("PDF generation error:", err);
      toast({ variant: 'destructive', title: 'Error', description: 'Failed to generate PDF.' });
    } finally {
      setIsDownloading(false);
    }
  };

  return { isDownloading, handleDownload };
}
